### ISSUE TITLE
`Catalog.get_job_by_id()` should be renamed to `catalog.job()`

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/qiskit-ibm-catalog#11]
## Description

Currently, if a user wants to fetch a job by id, they can use `catalog.get_job_by_id()`. This is inconsistent with Qiskit Runtime, where the expected interface is `service.job()`

**Comment by pandasa123** [comment]
I believe this was closed by #19? @paaragon / @Tansito?

**Comment by paaragon** [comment]
Yes! it was the same issue
