### ISSUE TITLE
Qedma single expectation value returned as 1D array and not the expected 0D array that runtime gives

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit-ibm-catalog#31]
### Steps to reproduce the problem

The same issue as #25 but for the Qedma function

### What is the current behavior?
Returns values such as `array([0.40210003])`

### What is the expected behavior?
The return should be a 0D array to match what Runtime and the IBM function return

**Comment by johannesgreiner** [comment]
this has been addressed in the latest release of `'qedma/qesem`. Propose to close the issue

**Comment by Tansito** [comment]
Of course, @johannesgreiner . I'm going to close this but if you see that any of the issues from partners opened is fixed feel free to close it. We can always reopen them 😄
